!coverage.py: This is a private format, don't read it directly!{"lines":{"/app/usolc/__init__.py":[1],"/app/usolc/usolc.py":[21,23,24,25,26,27,28,29,30,31,34,35,36,39,40,41,42,44,47,48,49,50,51,52,53,54,58,68,77,97,107,120,188,222,239,256,286,296,310,344,72,62,65,73,74,63,82,84,85,86,87,88,89,91,94,92,101,102,104,111,112,113,117,114,115,126,128,129,130,131,133,134,136,138,140,143,145,148,151,171,174,175,139,141,142,172,144,178,181,183,203,204,206,209,210,211,219,185,207,208,149,150,146,147,179,212,216,217,213,214,227,228,230,231,232,233,236,234,245,247,248,253,251,263,267,268,269,274,275,276,277,283,264,265,270,271,272,278,279,280,290,291,292,293,298,299,300,302,307,312,314,315,316,317,318,319,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,153,155,156,157,158,160,161,162,163,165,166,167,168,169,303,304],"/app/usolc/exceptions/__init__.py":[1],"/app/usolc/exceptions/pragmaline_notfound_error.py":[11,12],"/app/usolc/exceptions/noversion_available_by_sol.py":[11,12,13,14,15],"/app/usolc/exceptions/noversion_available_by_user.py":[11,12,13,14,15,16]}}